<?php
require 'config.php';
$json = '{
  "query":"'.Config::DB_SERVER.'query.php",
  "bank":{
      "deleteall":"'.Config::DB_SERVER.'bank/bank.deleteall.php",
      "show":"'.Config::DB_SERVER.'bank/bank.show.php",
      "showall":"'.Config::DB_SERVER.'bank/bank.showall.php",
      "transfer":"'.Config::DB_SERVER.'bank/bank.transfer.php",
      "update":"'.Config::DB_SERVER.'bank/bank.update.php"
    },
    "cart":{
      "add":"'.Config::DB_SERVER.'cart/cart.add.php",
      "remove":"'.Config::DB_SERVER.'cart/cart.remove.php",
      "save":"'.Config::DB_SERVER.'cart/cart.save.php"
    },
    "coupon":{
      "add":"'.Config::DB_SERVER.'coupon/coupon.add.php",
      "check":"'.Config::DB_SERVER.'coupon/coupon.check.php"
    },
    "customer":{
      "currentlist":"'.Config::DB_SERVER.'customer/customer.currentlist.php",
      "delete":"'.Config::DB_SERVER.'customer/customer.delete.php",
      "deleteall":"'.Config::DB_SERVER.'customer/customer.deleteall.php",
      "login":"'.Config::DB_SERVER.'customer/customer.login.php",
      "recommend":"'.Config::DB_SERVER.'customer/customer.recommend.php",
      "register":"'.Config::DB_SERVER.'customer/customer.register.php",
      "search1":"'.Config::DB_SERVER.'customer/customer.search1.php",
      "search":"'.Config::DB_SERVER.'customer/customer.search.php",
      "showall":"'.Config::DB_SERVER.'customer/customer.showall.php",
      "update":"'.Config::DB_SERVER.'customer/customer.update.php"
    },
    "featured":{
      "add":"'.Config::DB_SERVER.'featured/featured.add.php",
      "delete":"'.Config::DB_SERVER.'featured/featured.delete.php",
      "deleteall":"'.Config::DB_SERVER.'featured/featured.deleteall.php",
      "show":"'.Config::DB_SERVER.'featured/featured.show.php",
      "showall":"'.Config::DB_SERVER.'featured/featured.showall.php"
    },
    "feedback":{
      "add":"'.Config::DB_SERVER.'feedback/feedback.add.php",
      "getall":"'.Config::DB_SERVER.'feedback/feedback.getall.php",
      "getunseen":"'.Config::DB_SERVER.'feedback/feedback.getunseen.php",
      "markseen":"'.Config::DB_SERVER.'feedback/feedback.markseen.php",
      "remove":"'.Config::DB_SERVER.'feedback/feedback.remove.php"
    },
    "lists":{
      "check":"'.Config::DB_SERVER.'lists/lists.check.php",
      "delete":"'.Config::DB_SERVER.'lists/lists.delete.php",
      "deleteall":"'.Config::DB_SERVER.'lists/lists.deleteall.php",
      "insert":"'.Config::DB_SERVER.'lists/lists.insert.php",
      "listsby":"'.Config::DB_SERVER.'lists/lists.listsby.php",
      "setcurrent":"'.Config::DB_SERVER.'lists/lists.setcurrent.php",
      "share":"'.Config::DB_SERVER.'lists/lists.share.php",
      "show":"'.Config::DB_SERVER.'lists/lists.show.php",
      "showall":"'.Config::DB_SERVER.'lists/lists.showall.php",
      "sold":"'.Config::DB_SERVER.'lists/lists.sold.php"
    },
    "loyalty":{
      "get":"'.Config::DB_SERVER.'loyalty/loyalty.get.php",
      "usepoints":"'.Config::DB_SERVER.'loyalty/loyalty.usepoints.php"
    },
    "manager":{
      "add":"'.Config::DB_SERVER.'manager/manager.add.php",
      "login":"'.Config::DB_SERVER.'manager/manager.login.php",
      "remove":"'.Config::DB_SERVER.'manager/manager.remove.php"
    },
    "market":{
      "categories":"'.Config::DB_SERVER.'market/market.categories.php",
      "categorybrands":"'.Config::DB_SERVER.'market/market.categorybrands.php",
      "delete":"'.Config::DB_SERVER.'market/market.delete.php",
      "deleteall":"'.Config::DB_SERVER.'market/market.deleteall.php",
      "insert":"'.Config::DB_SERVER.'market/market.insert.php",
      "quickshow":"'.Config::DB_SERVER.'market/market.quickshow.php",
      "search1":"'.Config::DB_SERVER.'market/market.search1.php",
      "search":"'.Config::DB_SERVER.'market/market.search.php",
      "search":"'.Config::DB_SERVER.'market/market.search.php",
      "listsby":"'.Config::DB_SERVER.'market/market.listsby.php",
      "searchquick":"'.Config::DB_SERVER.'market/market.searchquick.php",
      "show":"'.Config::DB_SERVER.'market/market.show.php",
      "showall":"'.Config::DB_SERVER.'market/market.showall.php",
      "top":"'.Config::DB_SERVER.'market/market.top.php",
      "update":"'.Config::DB_SERVER.'market/market.update.php"
    },
    "notification":{
      "send":"'.Config::DB_SERVER.'notification/notification.send.php"
    },
    "orientation":{
      "showmap":"'.Config::DB_SERVER.'orientation/orientation.showmap.php",
      "path":"'.Config::DB_SERVER.'orientation/orientation.tsp.php"
    },
    "payment":{
      "gettodays":"'.Config::DB_SERVER.'payment/payment.gettodays.php",
      "receive":"'.Config::DB_SERVER.'payment/payment.receive.php",
      "receivecash":"'.Config::DB_SERVER.'payment/payment.receivecash.php",
      "receivecashfromunregistereduser":"'.Config::DB_SERVER.'payment/payment.receivecashfromunregistereduser.php",
      "send":"'.Config::DB_SERVER.'payment/payment.send.php"
    },
    "payment_completed":{
      "getall":"'.Config::DB_SERVER.'payment_completed/payment_completed.getall.php",
      "gettodays":"'.Config::DB_SERVER.'payment_completed/payment_completed.gettodays.php"
    }
}';
echo $json;
?>
